services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: infracheck_backend
    restart: unless-stopped
    ports:
      - '${BACKEND_PORT}:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: infracheck_db
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
volumes:
  db_data: